# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83101ecf4f01031d8d7d8872fc00fbbd7a977453dc20f53393e2070e369c7496db4404625e2334a7610cc12292fd21b18c03d145503b45c85a4a7fb47ba9fd33

test:
  secret_key_base: 5327931941a4cfebc4d3995f5b79fe268e96016a46a916ba20786f1d653048f4a3b8e96d04a21bdcbf3e1f0df47aa55ccf4df5d77b024bf78c1c12bdd9d54579

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
